### ISSUE TITLE
My phone 8 upi apps but array list empty

### ISSUE THREAD

**Issue by ankitsharma29** [Cshayan/react-native-upi-apps#3]
import React, { useEffect, useState } from 'react';
import { StyleSheet, View, Text, Image } from 'react-native';
import { getInstalledUPIAppList } from 'react-native-upi-apps';
import type { UPIApp } from 'react-native-upi-apps/src/types';

export default function TestCode() {
  const [result, setResult] = useState<UPIApp[]>([]);

  useEffect(() => {
    const getInstalledUPIApps = async () => {
      const appList = await getInstalledUPIAppList();
      console.log("appList",appList);
      
      setResult(appList);
    };

    getInstalledUPIApps();
  }, []);

  return (
    <View style={styles.container}>
      {result?.map((app) => (
        <View style={styles.listView}>
          <Image
            source={{ uri: `data:image/png;base64, ${app?.icon}` }}
            resizeMode="contain"
            style={styles.icon}
          />
          <Text>{app?.name}</Text>
        </View>
      ))}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  box: {
    width: 60,
    height: 60,
    marginVertical: 20,
  },
  listView: {
    flexDirection: 'column',
    flex: 1,
  },
  icon: {
    width: 50,
    height: 50,
  },
});

result:  
appList []

**Comment by Cshayan** [comment]
@ankitsharma29 can you please verify if the apps have UPI id enabled and active in the respective apps? I have seen this issue where even if app is installed in the device, it does not come under installed app lists if UPI id is inactive or not created.

**Comment by ankitsharma29** [comment]
I have created UPI Id on almost 5 apps but none came up in list

**Comment by Cshayan** [comment]
@ankitsharma29 can you please confirm if you have added the package names of the UPI apps in the Manifest file?

```
<queries>
    <package android:name="com.phonepe.app" />   <!-- phonpe  -->
    <package android:name="com.google.android.apps.nbu.paisa.user" /> <!-- gpay  -->
    <package android:name="net.one97.paytm" />  <!-- paytm  -->
    <package android:name="in.org.npci.upiapp" /> <!-- bhim  -->
    <package android:name="in.amazon.mShop.android.shopping" />   <!-- amazonpay  -->
    <package android:name="com.upi.axispay" />  <!-- axisbank  -->
    <package android:name="com.dreamplug.androidapp" /> <!-- cred  -->
    <package android:name="com.csam.icici.bank.imobile" /> <!-- icici  -->
    <package android:name="com.myairtelapp" /> <!-- my airtel -->
</queries>
```

**Comment by ankitsharma29** [comment]
yes,

**Comment by ankitsharma29** [comment]
What is the solution this issue?

**Comment by Cshayan** [comment]
@ankitsharma29 please share the sample code repo so that I can reproduce and debug it

**Comment by Cshayan** [comment]
Closing this since no response received. Please feel free to reopen it if issue still exists.
